'use client';

import { useMemo, useState } from 'react';

type Job = { id:number; company:string; role:string; base:string[]; industry:string; companyType:string; track:string; tags:string[]; updated:string; url:string };
const jobs: Job[] = [
  { id:1, company:'阿里巴巴', role:'前端开发工程师', base:['北京','杭州'], industry:'电商 · AI · 云计算', companyType:'大型民营科技', track:'前端', tags:['React','Node.js','2027届'], updated:'08-06', url:'https://campus-talent.alibaba.com/campus/position/199907720100' },
  { id:2, company:'阿里巴巴', role:'全栈开发工程师', base:['北京','杭州'], industry:'电商 · AI · 云计算', companyType:'大型民营科技', track:'全栈', tags:['Java','跨端','AI'], updated:'08-06', url:'https://campus-talent.alibaba.com/campus/position/199907720099' },
  { id:3, company:'阿里巴巴', role:'AI 前端开发工程师', base:['北京','杭州'], industry:'云计算 · 大模型', companyType:'大型民营科技', track:'前端', tags:['TypeScript','BFF','Agent'], updated:'08-06', url:'https://campus-talent.alibaba.com/campus/position/199907720012' },
  { id:4, company:'腾讯', role:'AI 全栈工程师', base:['多地','远程面试'], industry:'社交 · 游戏 · 云', companyType:'大型民营科技', track:'全栈', tags:['RAG','Agent','微服务'], updated:'已核验', url:'https://join.qq.com/post_detail.html?postid=1282707398326592512&activity=1289677489068326912' },
  { id:5, company:'字节跳动', role:'飞书全栈工程师', base:['杭州','深圳'], industry:'协同办公 · AI', companyType:'大型民营科技', track:'全栈', tags:['Android','iOS','服务端'], updated:'已核验', url:'https://jobs.bytedance.com/campus/position/7668317078402828597/detail' },
  { id:6, company:'网易有道', role:'全栈开发工程师', base:['北京'], industry:'教育科技 · AI', companyType:'上市互联网公司', track:'全栈', tags:['React/Vue','Java/Go','云原生'], updated:'08-27', url:'https://campus.163.com/app/detail/index?id=4860&projectId=103' },
  { id:7, company:'网易有道', role:'AI Agent 应用开发', base:['北京'], industry:'教育科技 · AI', companyType:'上市互联网公司', track:'前端', tags:['Web','移动端','Agent'], updated:'08-27', url:'https://campus.163.com/app/detail/index?id=4858&projectId=103' },
  { id:8, company:'网易有道', role:'AI 全栈工程师（数据）', base:['北京'], industry:'教育科技 · AI', companyType:'上市互联网公司', track:'全栈', tags:['Python','RAG','Flink'], updated:'08-27', url:'https://campus.163.com/app/detail/index?id=4861&projectId=103' },
];
const companyColors:Record<string,string>={阿里巴巴:'#ff6a2b',腾讯:'#397cff',字节跳动:'#171717',网易有道:'#e33b34'};

export default function Home(){
  const [query,setQuery]=useState(''); const [base,setBase]=useState('全部 Base'); const [track,setTrack]=useState('全部方向'); const [selectedId,setSelectedId]=useState(1); const [copied,setCopied]=useState(false);
  const selected=jobs.find(j=>j.id===selectedId)??jobs[0];
  const filtered=useMemo(()=>jobs.filter(job=>`${job.company}${job.role}${job.industry}${job.tags.join('')}`.toLowerCase().includes(query.toLowerCase())&&(base==='全部 Base'||job.base.includes(base))&&(track==='全部方向'||job.track===track)),[query,base,track]);
  const copySearchBrief=async()=>{await navigator.clipboard.writeText('请继续搜索 2027 届秋招岗位，扩大公司、行业、岗位方向和 Base 的覆盖范围；只收录官网可投递链接，并核验岗位仍可申请。我的个人关注方向以客户端、前端和全栈为主，但岗位库本身不限方向。');setCopied(true);setTimeout(()=>setCopied(false),1800)};
  return <main>
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">秋</span><span>秋招雷达 <small>2027</small></span></a><nav><a href="#jobs">岗位库</a><a href="#workflow">投递行动台</a><a href="#profile">我的材料</a></nav><button className="ghost" onClick={copySearchBrief}>{copied?'搜索指令已复制':'＋ 同步更多岗位'}</button></header>
    <section className="hero" id="top"><div><p className="eyebrow"><span/> 官网核验 · 2027 届秋招</p><h1>别再收藏岗位了，<br/><em>把它们投出去。</em></h1><p className="hero-copy">聚合不同方向的校招岗位，补全公司类型、行业和 Base。当前岗位以我的前端与全栈方向为主，但岗位库不限方向。</p></div><div className="scorecard"><div><strong>08</strong><span>已核验岗位</span></div><div><strong>04</strong><span>目标公司</span></div><div><strong>03</strong><span>核心城市</span></div><p>最后核验：2026.09.01 <span>LIVE</span></p></div></section>
    <section className="workspace" id="jobs"><div className="job-panel"><div className="panel-head"><div><p className="section-no">01 / 岗位库</p><h2>可投递岗位</h2></div><p className="result-count">显示 {filtered.length} / {jobs.length}</p></div><div className="filters"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索公司、岗位或技术栈"/></label><select value={base} onChange={e=>setBase(e.target.value)}><option>全部 Base</option><option>北京</option><option>杭州</option><option>深圳</option></select><select value={track} onChange={e=>setTrack(e.target.value)}><option>全部方向</option><option>前端</option><option>全栈</option></select></div><div className="job-list">{filtered.map(job=><button key={job.id} className={`job-row ${selectedId===job.id?'active':''}`} onClick={()=>setSelectedId(job.id)}><span className="company-icon" style={{background:companyColors[job.company]}}>{job.company[0]}</span><span className="job-main"><strong>{job.role}</strong><span>{job.company} · {job.companyType}</span><small>{job.industry}</small></span><span className="bases">{job.base.map(item=><i key={item}>⌖ {item}</i>)}</span><span className="tags">{job.tags.slice(0,2).map(tag=><i key={tag}>{tag}</i>)}</span><span className="arrow">↗</span></button>)}{filtered.length===0&&<div className="empty">没有匹配结果，换个关键词或清除筛选。</div>}</div></div>
      <aside className="action-panel" id="workflow"><p className="section-no">02 / BROWSER USE 行动台</p><div className="selected-company"><span style={{background:companyColors[selected.company]}}>{selected.company[0]}</span><div><small>当前选中</small><strong>{selected.company}</strong></div></div><h2>{selected.role}</h2><div className="fact-grid"><div><small>BASE</small><strong>{selected.base.join(' / ')}</strong></div><div><small>方向</small><strong>{selected.track}</strong></div><div><small>行业</small><strong>{selected.industry}</strong></div><div><small>状态</small><strong className="live">● 官网可投</strong></div></div><div className="steps"><p><b>1</b><span><strong>打开官方岗位页</strong><small>确认最新 JD 与申请截止时间</small></span></p><p><b>2</b><span><strong>匹配简历材料</strong><small>针对关键词生成投递版本</small></span></p><p><b>3</b><span><strong>协助填写与检查</strong><small>提交前由你最终确认</small></span></p></div><a className="primary" href={selected.url} target="_blank" rel="noreferrer">打开官网投递 <span>↗</span></a><button className="secondary" onClick={copySearchBrief}>{copied?'已复制，可交给我继续搜索':'让 Browser Use 补充同类岗位'}</button><p className="note">不会自动提交申请。涉及简历上传和最终投递时，会先让你确认。</p></aside></section>
    <section className="profile-strip" id="profile"><p className="section-no">03 / 我的材料</p><div><h2>把一份基础简历，变成每个岗位的投递版本。</h2><p>后续可在这里维护个人资料、简历版本和常见申请问题答案。</p></div><button disabled>材料库 · 下一版开放</button></section><footer><span>秋招雷达 2027</span><p>岗位信息来自企业招聘官网，请以官网实时状态为准。</p></footer>
  </main>
}
